twitter: ""
github: "https://github.com/TheNorthEestern"
instagram: "https://instagram.com/kacy.james"
linkedin: "https://www.linkedin.com/in/kacyjames/"
dribbble: ""
youtube: ""
facebook: ""
medium: ""
patreon: ""
paypal: ""
unsplash: ""
